api_platform:
    formats:
        jsonld: [ 'application/ld+json', 'application/json' ]
        multipart: [ 'multipart/form-data' ]
    docs_formats:
        jsonld: [ 'application/ld+json' ]
        jsonopenapi: [ 'application/vnd.openapi+json' ]
        html: [ 'text/html' ]
    title: Monekipe API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
